### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by NikitoDev** [inrl-official/inrl-bot-md#14]
Anyone can help me with this error?
First I type `npm install` then `npm start` but I get this error

PS C:\Users\User\Desktop\Bot> npm start

> whatsapp-botto-re@3.0.1 start C:\Users\User\Desktop\Bot
> node index.js

internal/modules/cjs/loader.js:968
  throw err;
  ^

Error: Cannot find module '@open-wa/wa-automate'
Require stack:
- C:\Users\User\Desktop\Bot\index.js
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:965:15)
    at Function.Module._load (internal/modules/cjs/loader.js:841:27)
    at Module.require (internal/modules/cjs/loader.js:1025:19)
    at require (internal/modules/cjs/helpers.js:72:18)
    at Object.<anonymous> (C:\Users\User\Desktop\Bot\index.js:1:20)
    at Module._compile (internal/modules/cjs/loader.js:1137:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1157:10)
    at Module.load (internal/modules/cjs/loader.js:985:32)
    at Function.Module._load (internal/modules/cjs/loader.js:878:14)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:71:12) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [ 'C:\\Users\\User\\Desktop\\Bot\\index.js' ]

**Comment by intkfthhffffghhbvfdsscghhnkkjjjjhhgg** [comment]
Please expline one more as possible

**Comment by multidivicebotforinrl-qrcodeforinrlalso** [comment]
> 

we will add a turtorial video after the time of termux with our termux supportive bot   _thanks_

**Comment by NikitoDev** [comment]
C:\Users\Nicolas\Desktop\BotV7>npm run test

> inrl-bot-md@1.0.0 test
> node index.js

C:\Users\Nicolas\Desktop\BotV7\node_modules\aes256\index.js:83
      throw new TypeError('Provided "encrypted" must be a non-empty string or buffer');
      ^

TypeError: Provided "encrypted" must be a non-empty string or buffer
    at Object.decrypt (C:\Users\Nicolas\Desktop\BotV7\node_modules\aes256\index.js:83:13)
    at Object.<anonymous> (C:\Users\Nicolas\Desktop\BotV7\index.js:2:11169)
    at Module._compile (node:internal/modules/cjs/loader:1099:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1153:10)
    at Module.load (node:internal/modules/cjs/loader:975:32)
    at Function.Module._load (node:internal/modules/cjs/loader:822:12)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:77:12)
    at node:internal/main/run_main_module:17:47

**Comment by inrl-official** [comment]
> 

It shown due to you are not provided session id to  acsess your whtsapp so fork and edit config.js, add session file then try?!

**Comment by lifeline127** [comment]
How do you get session id?  I made the QR code and scanned it, but it just says Device type MacOS and "Syncing. Keep app open."

**Comment by inrl-official** [comment]
> How do you get session id? I made the QR code and scanned it, but it just says Device type MacOS and "Syncing. Keep app open."

if you get ssid use it, otherwise rescan!!

**Comment by lifeline127** [comment]
You mean the QR code from here: https://inrl-web.onrender.com/viwe/friendpage

I've scanned both codes like 10 times.  Still just says same message?  Am I missing something?  Does it work on Apple version or only Android?

**Comment by inrl-official** [comment]
> You mean the QR code from here: https://inrl-web.onrender.com/viwe/friendpage
> 
> I've scanned both codes like 10 times. Still just says same message? Am I missing something? Does it work on Apple version or only Android?

no way give ss
https://inrl-web.onrender.com/info/wagroup
