### ISSUE TITLE
Runtime Errors

### ISSUE THREAD

**Issue by centdevs** [inrl-official/inrl-bot-md#72]
`Error: Timed Out
0|inrl  |     at /workspace/node_modules/@whiskeysockets/baileys/lib/Utils/generics.js:159:32 {
0|inrl  |   data: {
0|inrl  |     stack: 'Error\n' +
0|inrl  |       '    at promiseTimeout (/workspace/node_modules/@whiskeysockets/baileys/lib/Utils/generics.js:154:19)\n' +
0|inrl  |       '    at waitForMessage (/workspace/node_modules/@whiskeysockets/baileys/lib/Socket/socket.js:116:61)\n' +
0|inrl  |       '    at query (/workspace/node_modules/@whiskeysockets/baileys/lib/Socket/socket.js:139:22)\n' +
0|inrl  |       '    at getUSyncDevices (/workspace/node_modules/@whiskeysockets/baileys/lib/Socket/messages-send.js:169:30)\n' +
0|inrl  |       '    at /workspace/node_modules/@whiskeysockets/baileys/lib/Socket/messages-send.js:350:53\n' +
0|inrl  |       '    at Object.transaction (/workspace/node_modules/@whiskeysockets/baileys/lib/Utils/auth-utils.js:136:32)\n' +
0|inrl  |       '    at relayMessage (/workspace/node_modules/@whiskeysockets/baileys/lib/Socket/messages-send.js:279:30)\n' +
0|inrl  |       '    at WAConnection.sendMessage (/workspace/node_modules/@whiskeysockets/baileys/lib/Socket/messages-send.js:640:23)\n' +
0|inrl  |       '    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)'
0|inrl  |   },
0|inrl  |   isBoom: true,
0|inrl  |   isServer: false,
0|inrl  |   output: {
0|inrl  |     statusCode: 408,
0|inrl  |     payload: {
0|inrl  |       statusCode: 408,
0|inrl  |       error: 'Request Time-out',
0|inrl  |       message: 'Timed Out'
0|inrl  |     },
0|inrl  |     headers: {}
0|inrl  |   }
0|inrl  | }
0|inrl  | Error: Timed Out
0|inrl  |     at /workspace/node_modules/@whiskeysockets/baileys/lib/Utils/generics.js:159:32 {
0|inrl  |   data: {
0|inrl  |     stack: 'Error\n' +
0|inrl  |       '    at promiseTimeout (/workspace/node_modules/@whiskeysockets/baileys/lib/Utils/generics.js:154:19)\n' +
0|inrl  |       '    at waitForMessage (/workspace/node_modules/@whiskeysockets/baileys/lib/Socket/socket.js:116:61)\n' +
0|inrl  |       '    at query (/workspace/node_modules/@whiskeysockets/baileys/lib/Socket/socket.js:139:22)\n' +
0|inrl  |       '    at getUSyncDevices (/workspace/node_modules/@whiskeysockets/baileys/lib/Socket/messages-send.js:169:30)\n' +
0|inrl  |       '    at /workspace/node_modules/@whiskeysockets/baileys/lib/Socket/messages-send.js:350:53\n' +
0|inrl  |       '    at Object.transaction (/workspace/node_modules/@whiskeysockets/baileys/lib/Utils/auth-utils.js:136:32)\n' +
0|inrl  |       '    at relayMessage (/workspace/node_modules/@whiskeysockets/baileys/lib/Socket/messages-send.js:279:30)\n' +
0|inrl  |       '    at WAConnection.sendMessage (/workspace/node_modules/@whiskeysockets/baileys/lib/Socket/messages-send.js:640:23)\n' +
0|inrl  |       '    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)'
0|inrl  |   },
0|inrl  |   isBoom: true,
0|inrl  |   isServer: false,
0|inrl  |   output: {
0|inrl  |     statusCode: 408,
0|inrl  |     payload: {
0|inrl  |       statusCode: 408,
0|inrl  |       error: 'Request Time-out',
0|inrl  |       message: 'Timed Out'
0|inrl  |     },
0|inrl  |     headers: {}
0|inrl  |   }
0|inrl  | }`

this error keeps on recurring, sometimes it doesnt occur though but when it does the bot stops.  Right now i cant even scan the qrcode from [here](https://inrl-web.onrender.com/server/scan)

**Comment by Haker728** [comment]
Same with me

**Comment by inrl-official** [comment]
> `Error: Timed Out 0|inrl | at /workspace/node_modules/@whiskeysockets/baileys/lib/Utils/generics.js:159:32 { 0|inrl | data: { 0|inrl | stack: 'Error\n' + 0|inrl | ' at promiseTimeout (/workspace/node_modules/@whiskeysockets/baileys/lib/Utils/generics.js:154:19)\n' + 0|inrl | ' at waitForMessage (/workspace/node_modules/@whiskeysockets/baileys/lib/Socket/socket.js:116:61)\n' + 0|inrl | ' at query (/workspace/node_modules/@whiskeysockets/baileys/lib/Socket/socket.js:139:22)\n' + 0|inrl | ' at getUSyncDevices (/workspace/node_modules/@whiskeysockets/baileys/lib/Socket/messages-send.js:169:30)\n' + 0|inrl | ' at /workspace/node_modules/@whiskeysockets/baileys/lib/Socket/messages-send.js:350:53\n' + 0|inrl | ' at Object.transaction (/workspace/node_modules/@whiskeysockets/baileys/lib/Utils/auth-utils.js:136:32)\n' + 0|inrl | ' at relayMessage (/workspace/node_modules/@whiskeysockets/baileys/lib/Socket/messages-send.js:279:30)\n' + 0|inrl | ' at WAConnection.sendMessage (/workspace/node_modules/@whiskeysockets/baileys/lib/Socket/messages-send.js:640:23)\n' + 0|inrl | ' at process.processTicksAndRejections (node:internal/process/task_queues:95:5)' 0|inrl | }, 0|inrl | isBoom: true, 0|inrl | isServer: false, 0|inrl | output: { 0|inrl | statusCode: 408, 0|inrl | payload: { 0|inrl | statusCode: 408, 0|inrl | error: 'Request Time-out', 0|inrl | message: 'Timed Out' 0|inrl | }, 0|inrl | headers: {} 0|inrl | } 0|inrl | } 0|inrl | Error: Timed Out 0|inrl | at /workspace/node_modules/@whiskeysockets/baileys/lib/Utils/generics.js:159:32 { 0|inrl | data: { 0|inrl | stack: 'Error\n' + 0|inrl | ' at promiseTimeout (/workspace/node_modules/@whiskeysockets/baileys/lib/Utils/generics.js:154:19)\n' + 0|inrl | ' at waitForMessage (/workspace/node_modules/@whiskeysockets/baileys/lib/Socket/socket.js:116:61)\n' + 0|inrl | ' at query (/workspace/node_modules/@whiskeysockets/baileys/lib/Socket/socket.js:139:22)\n' + 0|inrl | ' at getUSyncDevices (/workspace/node_modules/@whiskeysockets/baileys/lib/Socket/messages-send.js:169:30)\n' + 0|inrl | ' at /workspace/node_modules/@whiskeysockets/baileys/lib/Socket/messages-send.js:350:53\n' + 0|inrl | ' at Object.transaction (/workspace/node_modules/@whiskeysockets/baileys/lib/Utils/auth-utils.js:136:32)\n' + 0|inrl | ' at relayMessage (/workspace/node_modules/@whiskeysockets/baileys/lib/Socket/messages-send.js:279:30)\n' + 0|inrl | ' at WAConnection.sendMessage (/workspace/node_modules/@whiskeysockets/baileys/lib/Socket/messages-send.js:640:23)\n' + 0|inrl | ' at process.processTicksAndRejections (node:internal/process/task_queues:95:5)' 0|inrl | }, 0|inrl | isBoom: true, 0|inrl | isServer: false, 0|inrl | output: { 0|inrl | statusCode: 408, 0|inrl | payload: { 0|inrl | statusCode: 408, 0|inrl | error: 'Request Time-out', 0|inrl | message: 'Timed Out' 0|inrl | }, 0|inrl | headers: {} 0|inrl | } 0|inrl | }`
> 
> this error keeps on recurring, sometimes it doesnt occur though but when it does the bot stops. Right now i cant even scan the qrcode from [here](https://inrl-web.onrender.com/server/scan)

fixed🤩

**Comment by centdevs** [comment]
> Same with me 

It's been fixed now
